# Generated by Django 5.2.10 on 2026-02-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=16)),
                ('midi_file', models.FileField(blank=True, null=True, upload_to='songs/midi/')),
                ('lrc_file', models.FileField(blank=True, null=True, upload_to='songs/lrc/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='songs/cover/')),
                ('lrc_offset', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='songs', to='songs.tag')),
            ],
        ),
    ]
