# Generated by Django 5.2.10 on 2026-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
