# Generated by Django 5.2.10 on 2026-02-01 13:02

import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='artist_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lrc_file',
            field=models.FileField(blank=True, null=True, upload_to=songs.models.lrc_upload_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='midi_file',
            field=models.FileField(blank=True, null=True, upload_to=songs.models.midi_upload_path),
        ),
    ]
