# Generated by Django 5.2.10 on 2026-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_artistindex_songindex_song_artist_no_alter_song_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongIndex',
        ),
        migrations.AddField(
            model_name='artistindex',
            name='next_song_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='song',
            name='song_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(blank=True, default='jp', max_length=32),
        ),
    ]
