import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const REVISION = '4f1b262fede3e999519e7e334bb25b779b506379'
const COMMIT_DATE = '2026-09-09T15:18:47Z'
const RAW_BASE = `https://raw.githubusercontent.com/ltgcgo/midi-db/${REVISION}/`
const OUTPUT_URL = new URL('../src/engine/plugins/xg-over-55/data/midiDb.generated.js', import.meta.url)
const GS_OUTPUT_URL = new URL('../src/engine/plugins/sc88-over-55/data/midiDb.generated.js', import.meta.url)
const SOURCE_FILES = Object.freeze({
  xgBank: 'bank/xg.tsv',
  gsBank: 'bank/gs.tsv',
  xgRoot: 'mane/syx/yamaha/xg.tsv',
  master: 'mane/syx/yamaha/xg/system/master.tsv',
  part: 'mane/syx/yamaha/xg/multi/part.tsv',
  effect: 'mane/syx/yamaha/xg/efx/global.tsv',
  drum: 'mane/syx/yamaha/xg/drumSet/note.tsv',
})

function parseTsv(text) {
  const [header, ...lines] = text.replace(/\r/g, '').trim().split('\n')
  const columns = header.split('\t')
  return lines.filter(Boolean).map((line) => {
    const values = line.split('\t')
    return Object.fromEntries(columns.map((column, index) => [column, values[index] || '']))
  })
}

function numeric(value) {
  const parsed = Number.parseInt(value, 10)
  return Number.isFinite(parsed) ? parsed : 0
}

function optionalNumeric(value) {
  return String(value || '').trim() === '' ? null : numeric(value)
}

function hexNumeric(value) {
  const parsed = Number.parseInt(value, 16)
  return Number.isFinite(parsed) ? parsed : 0
}

async function fetchSource(path) {
  const response = await fetch(`${RAW_BASE}${path}`)
  if (!response.ok) throw new Error(`midi-db fetch failed (${response.status}): ${path}`)
  return response.text()
}

function stableObject(entries) {
  return Object.fromEntries([...entries].sort(([left], [right]) => left.localeCompare(right)))
}

function emitModule(sourceTexts) {
  const bankRows = parseTsv(sourceTexts.xgBank)
  const voices = stableObject(bankRows.map((row) => [
    `${numeric(row.MSB)}:${numeric(row.LSB)}:${numeric(row.PRG)}`,
    [row.NME.trim(), optionalNumeric(row.LVL), optionalNumeric(row.ELC)],
  ]))
  const drumKits = stableObject(bankRows
    .filter((row) => numeric(row.MSB) === 127)
    .map((row) => [`${numeric(row.LSB)}:${numeric(row.PRG)}`, row.NME.trim()]))

  const nameRows = (key) => stableObject(parseTsv(sourceTexts[key]).map((row) => [
    hexNumeric(row.id).toString(16).padStart(2, '0'),
    row.name,
  ]))
  const hashes = stableObject(Object.entries(sourceTexts).map(([key, text]) => [
    SOURCE_FILES[key],
    createHash('sha256').update(text).digest('hex'),
  ]))

  return `// Generated by scripts/update-midi-db.mjs. Do not edit by hand.\n` +
    `// Data: CC-BY-SA-4.0, https://github.com/ltgcgo/midi-db\n\n` +
    `export const MIDI_DB_REVISION = ${JSON.stringify(REVISION)}\n` +
    `export const MIDI_DB_GENERATED_AT = ${JSON.stringify(COMMIT_DATE)}\n` +
    `export const MIDI_DB_SOURCE_HASHES = Object.freeze(${JSON.stringify(hashes, null, 2)})\n\n` +
    `export const XG_VOICES = Object.freeze(${JSON.stringify(voices, null, 2)})\n\n` +
    `export const XG_DRUM_KITS = Object.freeze(${JSON.stringify(drumKits, null, 2)})\n\n` +
    `export const XG_SYSEX_NAMES = Object.freeze(${JSON.stringify({
      master: nameRows('master'),
      part: nameRows('part'),
      effect: nameRows('effect'),
      drum: nameRows('drum'),
    }, null, 2)})\n`
}

function emitGsModule(sourceTexts) {
  const rows = parseTsv(sourceTexts.gsBank)
    .filter((row) => [0, 2, 3].includes(numeric(row.LSB)) && numeric(row.MSB) < 128)
  const voices = stableObject(rows.map((row) => {
    // midi-db's legacy GS table represents the capital tone with MSB 049.
    // Normalize that sentinel to the actual GS variation bank 0.
    const bank = numeric(row.MSB) === 49 ? 0 : numeric(row.MSB)
    return [
      `${numeric(row.LSB)}:${bank}:${numeric(row.PRG)}`,
      [row.NME.trim(), optionalNumeric(row.LVL), row.VXP?.trim() || ''],
    ]
  }))
  const hash = createHash('sha256').update(sourceTexts.gsBank).digest('hex')
  return `// Generated by scripts/update-midi-db.mjs. Do not edit by hand.\n` +
    `// Data: CC-BY-SA-4.0, https://github.com/ltgcgo/midi-db\n\n` +
    `export const MIDI_DB_REVISION = ${JSON.stringify(REVISION)}\n` +
    `export const MIDI_DB_GENERATED_AT = ${JSON.stringify(COMMIT_DATE)}\n` +
    `export const GS_BANK_SOURCE_HASH = ${JSON.stringify(hash)}\n` +
    `export const GS_VOICES = Object.freeze(${JSON.stringify(voices, null, 2)})\n`
}

const texts = Object.fromEntries(await Promise.all(Object.entries(SOURCE_FILES).map(async ([key, path]) => [
  key,
  await fetchSource(path),
])))
const generated = emitModule(texts)
const gsGenerated = emitGsModule(texts)

if (process.argv.includes('--stdout')) {
  process.stdout.write(generated)
} else if (process.argv.includes('--check')) {
  const current = await readFile(OUTPUT_URL, 'utf8').catch(() => '')
  const gsCurrent = await readFile(GS_OUTPUT_URL, 'utf8').catch(() => '')
  if (current !== generated || gsCurrent !== gsGenerated) {
    console.error(`Generated midi-db snapshot is stale: ${fileURLToPath(OUTPUT_URL)}`)
    process.exitCode = 1
  }
} else {
  await writeFile(OUTPUT_URL, generated)
  await writeFile(GS_OUTPUT_URL, gsGenerated)
  console.log(`Updated ${fileURLToPath(OUTPUT_URL)} from midi-db ${REVISION}`)
  console.log(`Updated ${fileURLToPath(GS_OUTPUT_URL)} from midi-db ${REVISION}`)
}
