# Generated by Django 5.2.10 on 2026-02-01 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_combo', models.PositiveIntegerField(blank=True, null=True)),
                ('play_mode', models.CharField(blank=True, max_length=32)),
                ('difficulty', models.CharField(blank=True, max_length=32)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='songs.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['song', '-score', '-updated_at'], name='scores_scor_song_id_2a77db_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'song'), name='unique_best_score_per_user_song')],
            },
        ),
    ]
