# Generated by Codex on 2026-02-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_best_score_per_user_song',
        ),
    ]
