# Generated by Django 5.2.10 on 2026-02-03 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_delete_songindex_artistindex_next_song_no_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_combo', models.PositiveIntegerField(blank=True, null=True)),
                ('f0_curve', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='songs.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PlayHistory',
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['user', '-created_at'], name='users_score_user_id_9a457d_idx'),
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['song', '-created_at'], name='users_score_song_id_14121a_idx'),
        ),
    ]
