# Generated by Django 5.2.10 on 2026-02-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_scorehistory_delete_playhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorehistory',
            name='technique_counts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
